// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_content_delivery_bucket": "jasminetea-20200405190914-hostingbucket-production",
    "aws_content_delivery_bucket_region": "ap-southeast-1",
    "aws_content_delivery_url": "http://jasminetea-20200405190914-hostingbucket-production.s3-website-ap-southeast-1.amazonaws.com",
    "aws_cognito_identity_pool_id": "ap-southeast-1:199932f3-b890-4082-8d87-034331a4279e",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_FumP22eHI",
    "aws_user_pools_web_client_id": "7is02t7rbe23893mme1st5j9vf",
    "oauth": {}
};


export default awsmobile;
